version: "3.9"
services:
  nba_scoring_bot:
    container_name: nba_bot_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/code
    command: python3 main.py


networks:
  default:
    driver: bridge
