name: Run NBA Scoring Bot

on:
  schedule:
    - cron: "0 22 * * *"  # Runs at 4 PM CT (10 PM UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run NBA Scoring Bot
        run: |
          docker-compose up -d
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}


